repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: [{id: black}]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks: [{id: isort}]
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks: [{id: flake8}]
- repo: local
  hooks:
    - id: smoke
      name: gsgsim smoke
      entry: scripts/smoke.sh
      language: system
      pass_filenames: false

repos:
- repo: local
  hooks:
    - id: check-rules-import-usage
      name: check rules imports are used
      entry: scripts/check_rules_import_usage.py
      language: system
      pass_filenames: false
    - id: ban-deprecated-symbols
      name: ban deprecated symbols
      entry: scripts/check_deprecated_symbols.sh
      language: system
      pass_filenames: false
