[tool.black]
line-length = 200
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 200
multi_line_output = 3
include_trailing_comma = true

[tool.pylint.'MESSAGES CONTROL']
disable = ["C0301"]  # line-too-long
