# ui/base.py
from __future__ import annotations
from typing import Protocol, Optional
from gsg_sim import GameState, Player  # engine types

class UI(Protocol):
    def render_board(self, gs: GameState) -> None: ...
    def render_hand(self, p: Player, label: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def run_loop(self, gs: GameState) -> None: ...